package models;

/**
 * Created by haroldo on 31/07/14.
 */
public enum  Estado {

        ACRE, ALAGOAS, AMAZONAS, BAHIA, CEARA, DISTRITO_FEDERAL, ESPIRITO_SANTO, GOIAS, MINAS_GERAIS, MATO_GROSSO, MATO_GROSSO_SUL, PARA, PARAIBA, PERNAMBUCO, PIAUI, PARANA, RIO_DE_JANEIRO, RONDONIA, RIO_GRANDE_SUL, RORAIMA, SANTA_CATARINA, SERGIPE, SAO_PAULO, TOCANTINS
}
