package models;

/**
 * Created by haroldo on 31/07/14.
 */
public enum  Estado {

        ACRE, ALAGOAS, AMAZONAS, BAHIA, CEARÁ, DISTRITO_FEDERAL, ESPÍRITO_SANTO, GOIÁS, MINAS_GERAIS, MATO_GROSSO, MATO_GROSSO_SUL, PARÁ, PARAÍBA, PERNAMBUCO, PIAUÍ, PARANÁ, RIO_DE_JANEIRO, RONDÕNIA, RIO_GRANDE_SUL, RORAIMA, SANTA_CATARINA, SERGIPE, SÃO_PAULO, TOCANTINS
}
